import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Slurpee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/IconSlurpee.ico" />
      </Head>

      <div className="flex justify-center relative mx-auto mt-20 w-3/5 h-32 pb-10">
        <Image
          src="/slurpee-logo.png"
          alt="Slurpee Logo"
          fill="true"
          className="object-contain"
        />
      </div>
      <div className="flex justify-center relative mx-auto w-32 h-32">
        <Image
          src="/7-Eleven-Logo.png"
          alt="7 Eleven Logo"
          fill="true"
          className="object-contain"
        />
      </div>
      <div className="header-slogan py-20 md:py-10 px-4 lg:px-10 xl:px-20">
        <h1 className="font-bold text-center">
          <span className="text-[2.5rem] md:text-[3rem]">
            <span className="text-[color:var(--pink)]">Loved</span> by {''}
            <span className="text-[color:var(--casal)]">everyone</span>
            <br /> from kids to adults, <br />
          </span>
          <span className="text-[1.5rem]">
            is more than a frozen drink. It’s a <br /> lifestyle.
          </span>
        </h1>
      </div>

      <div className="container md:py-20 mx-auto lg:px-10 xl:px-20">
        <div className="flex flex-wrap justify-center text-center font-bold">
          <div className="w-full md:w-[33%] p-5">
            <div className="h-48 relative">
              <Image
                src="/logo1.svg"
                alt="7 Eleven Logo"
                fill="true"
                className="object-contain"
              />
            </div>
            <h2 className="text-2xl py-5">The Sales MVP</h2>
            <p>
              Detroit, Michigan, holds the record for the <br /> top Slurpee®
              drink Sales in the US.
            </p>
          </div>
          <div className="w-full md:w-[33%] p-5">
            <div className="h-48 relative">
              <Image
                src="/logo2.svg"
                alt="7 Eleven Logo"
                fill="true"
                className="object-contain"
              />
            </div>
            <h2 className="text-2xl py-5">Smooth Operator</h2>
            <p>
              Slurpee® drinks are served at a frosty 28 degrees. <br /> Each
              drink is made into a fizzy, fluffy frozen perfection .
            </p>
          </div>
          <div className="w-full md:w-[33%] p-5">
            <div className="h-48 relative">
              <Image
                src="/logo3.svg"
                alt="7 Eleven Logo"
                fill="true"
                className="object-contain"
              />
            </div>
            <h2 className="text-2xl py-5">Flavor Faves</h2>
            <p>The most popular flavors are Coca-Cola and Cherry.</p>
          </div>
          <div className="w-full md:w-[33%] p-5">
            <div className="h-48 relative">
              <Image
                src="/logo4.svg"
                alt="7 Eleven Logo"
                fill="true"
                className="object-contain"
              />
            </div>
            <h2 className="text-2xl py-5">Up, Up and Away!</h2>
            <p>In 2021, 7-Eleven sent the first Slurpee® drink to space.</p>
          </div>
          <div className="w-full md:w-[33%] p-5">
            <div className="h-48 relative">
              <Image
                src="/logo5.svg"
                alt="7 Eleven Logo"
                fill="true"
                className="object-contain"
              />
            </div>
            <h2 className="text-2xl py-5">Cool Cups</h2>
            <p>
              7-Eleven began introducing Slurpee® collectors’ cups in 1972.
              Special Slurpee drink cups have featured monsters, rock ‘n’ roll
              stars, and endangered species.{' '}
            </p>
          </div>
        </div>
      </div>

      <div className="container py-20 px-4 mx-auto lg:px-10 xl:px-20 font-bold leading-8">
        <div className="relative flex mt-20 w-1/2 md:w-1/5 h-32 pb-10">
          <Image
            src="/slurpee-logo.png"
            alt="Slurpee Logo"
            fill="true"
            className="object-contain object-left"
          />
        </div>
        <h2 className="text-3xl my-5">HISTORY</h2>
        <p className="max-w-[45ch]">
          In the late 1950s, Omar Knedlik’s soda fountain at his restaurant
          broke. He stashed some soda pop in the freezer and had the idea to
          turn frozen soda into a beverage. He used parts from an automobile air
          conditioner to build a simple frozen beverage machine. Since then,
          Slurpee has become a beloved beverage of millions, a pop culture icon,
          and 7-Eleven’s most well-known proprietary brand. From its beginning,
          with kooky flavor names like Fulla Bulla, Blue Blunder and Awa Awa
          Ukulele, Slurpee® has been keeping it &quot;cool&quot; for
          generations.
        </p>
      </div>
    </>
  );
}
